### ISSUE TITLE
Kindly provide an use case for a inexperianced client side developer.

### ISSUE THREAD

**Issue by Zuhayer** [bhoodream/Chameleon.js#1]
I am a server side php developer, not proficient with css, jquery or js. I have tried to use Chameleon.js by trying to replicate the Demo, but still I have been unsuccessful. 

e.g. in $(".chmln").chameleon(settings); I do not know what the settings variable holds. I tried to inspect the [demo](https://vadimfedorov.ru/lab/chameleon-js/) and view its source. 

Could you add a simple example with a html, css, .js file?

**Comment by bhoodream** [comment]
Hello, Zuhayer. Of course, in the near future I will add examples! :)

In particular, `$(".chmln").chameleon();` you can use without any settings.

Try this `html`:
```
<div class="chmln">
<h2 class="chmln1">Title text</h2>
<blockquote class="chmln2">
Blockquote text
<cite class="chmln3">Cite text</cite>
</blockquote>
<p class="chmln4">Paragraph text.</p>
<img class="chmln__img" src="your-image-src-here" alt="Chameleon Image">
</div>
```

**Comment by hopesandshadows** [comment]
Likewise I am struggling to piece this together to create a colour palette. This looks like an interesting project so I would welcome an example html page.
