### ISSUE TITLE
Demo page does not appear

### ISSUE THREAD

**Issue by schutze** [bhoodream/Chameleon.js#2]
The https://vadimfedorov.ru/lab/chameleon-js demo page does not appear. 

The connection has timed out
The server at vadimfedorov.ru is taking too long to respond.

- The site could be temporarily unavailable or too busy. Try again in a few moments.
- If you are unable to load any pages, check your computer’s network connection.
- If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by bhoodream** [comment]
Hello, tell me please from which country are you trying to access the demo page? Also, which browser are you using and which system? And when did this happen and is it repeated now?

**Comment by bhoodream** [comment]
It looked like it was just some kind of a misunderstanding.

**Comment by schutze** [comment]
@bhoodream Sorry bud, I needed a little more time to reply.  The demo page still does not appear when requested from Windows 7 in U.S.A. I've tried Firefox 54.0, IE 11.0.9600.18665CO, Chrome 58.0.3029.110 (64-bit), and Version 59.0.3071.109 (Official Build) (64-bit).  They all have the same problem.  I am on my company VPN right now but I can try directly from my ISP sometime soon if that would help.

Chrome gave some additional information: ERR_CONNECTION_TIMED_OUT

**Comment by bhoodream** [comment]
@schutze try please :)

**Comment by schutze** [comment]
@bhoodream Sorry it took so long to respond but the demo page does appear when I am not connected to my company's VPN so the VPN must be blocking it somehow.
